import type { Concert } from '@/lib/damai-crawler';

export type ConcertSource = 'damai' | 'moretickets' | 'moretickets-global';
export type OpportunityStatus = 'new' | 'watching' | 'qualified' | 'ignored' | 'converted';
export type ProjectStatus = 'active' | 'on_hold' | 'completed' | 'cancelled';
export type ProjectStage = 'planning' | 'outreach' | 'quoted' | 'confirmed' | 'execution' | 'review';
export type ProjectPriority = 'low' | 'normal' | 'high';
export type ProjectTaskStatus = 'todo' | 'in_progress' | 'done' | 'skipped';
export type CalendarEventKind = 'concert' | 'project_task';

export interface CalendarEvent {
  id: string;
  title: string;
  start: Date;
  end: Date;
  allDay?: boolean;
  kind?: CalendarEventKind;
  resource: Concert;
}

export interface ProjectTask {
  id: string;
  projectId: string;
  title: string;
  taskType: string;
  status: ProjectTaskStatus;
  dueDate: string | null;
  relativeOffsetDays: number | null;
  sortOrder: number;
  autoGenerated: boolean;
  notes: string;
  completedAt: number | null;
}

export interface Project {
  id: string;
  concertId: string | null;
  title: string;
  artist: string;
  city: string;
  venue: string;
  concertDate: string | null;
  status: ProjectStatus;
  stage: ProjectStage;
  owner: string;
  priority: ProjectPriority;
  notes: string;
  quoteAmount: number | null;
  quoteStatus: string | null;
  nextFollowUpAt: string | null;
  createdAt: number;
  updatedAt: number;
  tasks: ProjectTask[];
  contacts: Contact[];
  followUps: FollowUp[];
}

export interface Contact {
  id: string;
  name: string;
  role: string;
  phone: string;
  email: string;
  wechat: string;
  company: string;
  notes: string;
  createdAt: number;
  updatedAt: number;
}

export interface FollowUp {
  id: string;
  projectId: string;
  content: string;
  followUpDate: string | null;
  createdAt: number;
}
